Add missing parameter 'hba_entry_order'
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Unknown variable: 'barman::hba_entry_order'. (file: /etc/puppetlabs/code/environments/production/modules/barman/manifests/server.pp, line: 277, column: 24) on node backup
```